name: trademale
description: unergraduationProject

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  awesome_dialog: ^3.1.0
  expandable_text: ^2.3.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  lottie: ^2.7.0
  persistent_bottom_nav_bar: ^5.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/Animation - 1708433147163.json

  fonts:
    - family: Schyler
      fonts:
        - asset: assets/fonts/Anta-Regular.ttf
        # - asset: assets/fonts/Schyler-Italic.ttf
        #   style: italic
